name: Deploy frontend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin     

      - name: Clean up Docker
        run: docker system prune -af --volumes

      - name: Build Docker Image
        run: |
          docker build --no-cache -t abhinavdogra003768/frontend:latest

      - name: Publish Image to Docker Hub
        run: docker push abhinavdogra003768/frontend:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull abhinavdogra003768/frontend:latest

      - name: Stop and Remove Old Container
        run: |
          if [ $(sudo docker ps -aq -f name=frontend-container) ]; then
            echo "Stopping and removing existing container..."
            sudo docker rm -f frontend-container
          else
            echo "No existing container found."
          fi

      - name: Remove Old Images
        run: |
          old_images=$(sudo docker images -q abhinavdogra003768/frontend | tail -n +2)
          if [ -n "$old_images" ]; then
            echo "Removing old images..."
            echo "$old_images" | xargs sudo docker rmi -f
          else
            echo "No old images to remove."
          fi

      - name: Run New Docker Container
        run: |
          docker run -d --name frontend-container -p 80:80 abhinavdogra003768/frontend:latest
