name: Deploy frontend

on: 
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t abhinavdogra003768/frontend:latest \
            --build-arg VITE_API_BASE_URL='http://13.126.144.181:8000' .

      - name: Publish Image to Docker Hub
        run: docker push abhinavdogra003768/frontend:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull abhinavdogra003768/frontend:latest

      - name: Force Stop and Remove Old Container (if exists)
        run: |
          if [ $(sudo docker ps -aq -f name=frontend-container) ]; then
            echo "Removing existing container..."
            sudo docker rm -f frontend-container
          else
            echo "No existing container found."
          fi

      - name: Run New Docker Container
        run: |
          docker run -d --name frontend-container -p 80:80 \
            -e VITE_API_BASE_URL='http://13.126.144.181:8000' \
            abhinavdogra003768/frontend:latest
