name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      
      - name: Build Docker Image
        run: docker build -t abhinavdogra003768/frontend:latest --build-arg VITE_BackendURL='${{ secrets.VITE_BackendURL }}' .

      - name: Cleanup Docker on Builder
        run: |
          docker image prune -f
          docker container prune -f
          docker volume prune -f

      - name: Publish Image to Docker Hub
        run: docker push abhinavdogra003768/frontend:latest 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull abhinavdogra003768/frontend:latest 
        
      - name: Stop and Remove Old Container (if exists)
        run: |
          docker stop frontend-container || true
          docker rm frontend-container || true
        
      - name: Remove Unused Images and Containers
        run: |
          docker image prune -f
          docker container prune -f
          docker volume prune -f
        
      - name: Run New Docker Container
        run: |
          docker run -d -p 5173:80 --name frontend-container abhinavdogra003768/frontend:latest
