name: Deploy Vite Frontend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t abhinavdogra003768/frontend:latest \
            --build-arg VITE_API_BASE_URL='http://13.201.189.166:8000' .

      - name: Publish Image to Docker Hub
        run: docker push abhinavdogra003768/frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull abhinavdogra003768/frontend:latest

      - name: Delete Old Container (if exists)
        run: docker rm -f frontend-container || true

      - name: Run Docker Container (Vite)
        run: |
          docker run -d --name frontend-container -p 5173:5173 \
            -e VITE_API_BASE_URL='http://13.201.189.166:8000' \
            abhinavdogra003768/frontend:latest
